LOAD DATA
INFILE 'recolte_augmente_1M.dat'
INTO TABLE recolteR
APPEND
FIELDS TERMINATED BY '|' TRAILING NULLCOLS
(
  Nprod  INTEGER EXTERNAL NULLIF Nprod=BLANKS,
  Nvin   INTEGER EXTERNAL NULLIF Nvin=BLANKS,
  Annee  INTEGER EXTERNAL NULLIF Annee=BLANKS,
  Qte     CHAR            NULLIF Qte=BLANKS  "TO_NUMBER(:Qte)"
)
 
